export const ROUTES = {
	HOME: '/',
	ACCOUNT_DUMMY: '/(accounts)/account',
	LOGIN: '/login',
	REGISTER: '/register',
	ACCOUNT: '/account',
	ITINERARY: '/itinerary',
	ITINERARY_RESULT: '/itineraries',
	TRACKING: '/track',
	ADMIN: '/admin',
	CREATE_COMPANY: '/admin/create-company',
	CREATE_CONTACT: '/admin/create-contact',
	CREATE_USER: '/admin/create-user',
	API_RESEND_REGISTER: 'https://marines-services.vercel.app/email/register',
	API_LOGIN: '/auth/login',
	API_REGISTER_NEW_USER: '/auth/register',
	API_USER_VERIFY: '/auth/verify',
	API_GET_PROFILE: '/auth/profile',
	API_LOGOUT: '/auth/logout',
	API_CREATE_USER: '/users',
	API_ROUTE: 'https://marines-services.vercel.app',
};
