// Mock data
import { ZimTrackingResult } from '@/lib/types/zim/zimTypes';
import { HapagEvent } from '@/lib/types/hapag/hapagTypes';

export const hapagTrackingResult200: HapagEvent[] = [
	{
		eventCreatedDateTime: '2025-07-10T04:14:18.265Z',
		eventType: 'TRANSPORT',
		eventClassifierCode: 'ACT',
		eventDateTime: '2025-07-10T04:14:18.265Z',
		transportEventTypeCode: 'ARRI',
		transportCall: {
			transportCallID: '123e4567-e89b-12d3-a456-426614174000',
			exportVoyageNumber: '2103S',
			importVoyageNumber: '2103N',
			UNLocationCode: 'FRPAR',
			facilityTypeCode: 'POTE',
			modeOfTransport: 'VESSEL',
			location: {
				locationName: 'Eiffel Tower',
				UNLocationCode: 'FRPAR',
				address: {
					name: 'Henrik',
				},
			},
			vessel: {
				vesselIMONumber: '9321483',
				vesselName: 'King of the Seas',
			},
		},
	},
	{
		eventCreatedDateTime: '2025-07-10T04:14:18.265Z',
		eventType: 'SHIPMENT',
		eventClassifierCode: 'ACT',
		eventDateTime: '2025-07-10T04:14:18.265Z',
		shipmentEventTypeCode: 'ISSU',
		documentID: 'HLCUGDN0000000',
		documentTypeCode: 'TRD',
	},
	{
		eventCreatedDateTime: '2025-07-10T04:14:18.265Z',
		eventType: 'EQUIPMENT',
		eventClassifierCode: 'ACT',
		eventDateTime: '2025-07-10T04:14:18.265Z',
		equipmentEventTypeCode: 'LOAD',
		equipmentReference: 'APZU4812090',
		eventLocation: {
			locationName: 'Eiffel Tower',
			UNLocationCode: 'FRPAR',
			address: {
				name: 'Henrik',
			},
		},
		transportCall: {
			transportCallID: '123e4567-e89b-12d3-a456-426614174000',
			exportVoyageNumber: '2103S',
			importVoyageNumber: '2103N',
			UNLocationCode: 'FRPAR',
			facilityTypeCode: 'POTE',
			modeOfTransport: 'VESSEL',
			location: {
				locationName: 'Eiffel Tower',
				UNLocationCode: 'FRPAR',
				address: {
					name: 'Henrik',
				},
			},
			vessel: {
				vesselIMONumber: '9321483',
				vesselName: 'King of the Seas',
			},
		},
	},
];

export const zimTracingResult200: ZimTrackingResult = {
	finalETA: {
		etaDescription: null,
		etaValue: '2023-09-22T09:00:00Z',
		etaValueDate: '2023-09-22T09:00:00Z',
	},
	routeDetails: [
		{
			arrivalDateTz: '2023-08-11T07:00:00Z',
			legOrder: 2,
			portCodeFrom: 'CNNKG',
			countryCodeFrom: 'CN',
			portNameTo: 'SHANGHAI (SH)',
			portCodeTo: 'CNSHA',
			voyage: '23',
			leg: 'E',
			sailingDateDT: '2023-08-09T11:00:00Z',
			portNameFrom: 'NANJING (JS)',
			vessel: 'UU3',
			countryNameTo: "CHINA. PEOPLE'S REPUBLIC",
			countryNameFrom: "CHINA. PEOPLE'S REPUBLIC",
			sailingDateTz: '2023-08-09T11:00:00Z',
			arrivalDateDT: '2023-08-11T07:00:00Z',
			countryCodeTo: 'CN',
			vesselName: 'WU XIANG 76',
		},
		{
			arrivalDateTz: '2023-09-08T09:00:00Z',
			legOrder: 3,
			portCodeFrom: 'CNSHA',
			countryCodeFrom: 'CN',
			portNameTo: 'BALBOA',
			portCodeTo: 'PABLB',
			voyage: '3',
			leg: 'E',
			sailingDateDT: '2023-08-17T04:00:00Z',
			portNameFrom: 'SHANGHAI (SH)',
			vessel: 'ADA',
			countryNameTo: 'PANAMA',
			countryNameFrom: "CHINA. PEOPLE'S REPUBLIC",
			sailingDateTz: '2023-08-17T04:00:00Z',
			arrivalDateDT: '2023-09-08T09:00:00Z',
			countryCodeTo: 'PA',
			vesselName: 'ZIM BANGKOK',
		},
		{
			arrivalDateTz: '2023-09-22T09:00:00Z',
			legOrder: 4,
			portCodeFrom: 'PABLB',
			countryCodeFrom: 'PA',
			portNameTo: 'SAN ANTONIO',
			portCodeTo: 'CLSAI',
			voyage: '447',
			leg: 'S',
			sailingDateDT: '2023-09-10T06:00:00Z',
			portNameFrom: 'BALBOA',
			vessel: 'QDN',
			countryNameTo: 'CHILE',
			countryNameFrom: 'PANAMA',
			sailingDateTz: '2023-09-10T06:00:00Z',
			arrivalDateDT: '2023-09-22T09:00:00Z',
			countryCodeTo: 'CL',
			vesselName: 'EM SPETSES',
		},
	],
	bkBlDetails: {
		placeDeliveryCountryCode: null,
		countryNamePortOfLoading: "CHINA. PEOPLE'S REPUBLIC",
		placeAcceptance: null,
		portOfDischarge: 'SAN ANTONIO',
		countryCodePortOfDischarge: 'CL',
		placeDeliveryCountryName: null,
		countryNamePlaceAcceptance: null,
		bookingReference: 'ZIMUNNJ1011275',
		placeAcceptanceCode: null,
		blReference: 'ZIMUNNJ1011275',
		countryNamePortOfDischarge: 'CHILE',
		portOfDischargeCode: 'CLSAI',
		placeDeliveryCode: null,
		placeDelivery: null,
		countryCodePlaceAcceptance: null,
		portOfLoadingCode: 'CNNKG',
		portOfLoading: 'NANJING (JS)',
		countryCodePortOfLoading: 'CN',
		consContainerList: [
			{
				containerNumber: 'FSCU8155163',
				containerTypeSize: 'HC40',
				containerEventsList: [
					{
						countryCodePort: 'CN',
						activityDate: '2023-08-18T11:38:00Z',
						port: 'SHANGHAI (SH)',
						vessel: 'ADA',
						eventName:
							'Vessel departure from first Transshipment Port to next Transshipment Port',
						portCode: 'CNSHA',
						countryPort: "CHINA. PEOPLE'S REPUBLIC",
						activityDateTz: '2023-08-18T11:38:00Z',
						vesselName: 'ZIM BANGKOK',
						voyage: '3',
						leg: 'E',
					},
					{
						countryCodePort: 'CN',
						activityDate: '2023-08-20T12:57:00Z',
						port: 'SHANGHAI (SH)',
						vessel: 'ADA',
						eventName:
							'Container was loaded at Transshipment Port to Transshipment Port',
						portCode: 'CNSHA',
						countryPort: "CHINA. PEOPLE'S REPUBLIC",
						activityDateTz: '2023-08-20T12:57:00Z',
						vesselName: 'ZIM BANGKOK',
						voyage: '3',
						leg: 'E',
					},
				],
			},
		],
	},
};
